baseurl = "https://ngacareer.github.io/public/"
languageCode = "en-us"
title = "ngacareer on github"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "NgaCareer"
    #avatar = "avatar.jpg"
    avatar = "ngacareer.jpg"
    # avatarDescription = "My avatar description"
    #favicon = "favicon.ico"
    favicon = "icon-ngacareer.png"
    description = """
        Welcome to the NgaCareer Open Source Community. Click on the "edit" icon below to see contributors list. Fork the repo and check the README.md
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "contributors"
    #name = "contributors"
    pre = "<i class='fa fa-edit fa-lg'></i>"
    url = "/contributors"
    weight = 1

[[menu.main]]
    identifier = "conferences"
    #name = "Conferences"
    pre = "<i class='fa fa-blog fa-lg'></i>"
    url = "conferences/conferences/"
    weight = 2

[[menu.main]]
    identifier = "blog"
    # name = "blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "https://medium.com/NgaCareer"
    #url = "/blog/"
    weight = 3

[[menu.main]]
    identifier = "twitter"
    # name = "twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/ngacareer"
    weight = 4

[[menu.main]]
    identifier = "github"
    # name = "gitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/ngacareer"
    weight = 5

[[menu.main]]
    identifier = "facebook"
    # name = "facebook"
    pre = "<i class='fab fa-facebook fa-lg'></i>"
    url = "https://www.facebook.com/ngacareer"
    weight = 6

[[menu.main]]
    identifier = "youtube"
    # name = "youtube"
    pre = "<i class='fab fa-youtube fa-lg'></i>"
    url = "https://www.youtube.com/ngacareer"
    weight = 7

[[menu.main]]
    identifier = "instagram"
    # name = "instagram"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/ngacareer"
    weight = 8

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:ms@ngacareer.com"
    weight = 9
