baseurl = "https://ngacareer.github.io/public/"
title = "ngacareer on github"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "NgaCareer"
    #avatar = "avatar.jpg"
    avatar = "ngacareer.jpg"
    # avatarDescription = "My avatar description"
    #favicon = "favicon.ico"
    favicon = "icon-ngacareer.png"
    description = """
        Welcome to the NgaCareer Open Source Community. Click on the "edit" icon below to see contributors list. Fork the repo and check the README.md
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "Contributors"
    #name = "Contributors"
    pre = "<i class='fa fa-edit fa-lg'></i>"
    url = "/contributors"
    weight = 10

[[menu.main]]
    identifier = "Conferences"
    #name = "Conferences"
    pre = "<i class='fa fa-blog fa-lg'></i>"
    url = "/conferences/conferences"
    weight = 20

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "https://medium.com/NgaCareer"
    weight = 30

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/ngacareer"
    weight = 40

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/ngacareer"
    weight = 50

[[menu.main]]
    identifier = "Facebook"
    # name = "Facebook"
    pre = "<i class='fab fa-facebook fa-lg'></i>"
    url = "https://www.facebook.com/ngacareer"
    weight = 60

[[menu.main]]
    identifier = "Youtube"
    # name = "Facebook"
    pre = "<i class='fab fa-youtube fa-lg'></i>"
    url = "https://www.youtube.com/ngacareer"
    weight = 70

[[menu.main]]
    identifier = "Instagram"
    # name = "Instagram"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/ngacareer"
    weight = 80

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:ms@ngacareer.com"
    weight = 90
